production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: 127.0.0.1
  username: dumbocms
  password: dumbo
  database: dumbocms
  reconnect: true

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: 127.0.0.1
  username: root
  password: root
  database: dumbocms_development
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: 127.0.0.1
  username: root
  password: root
  database: dumbocms_test
  reconnect: true
