dumbocms:
  app: 'DumboCMS'
  homepage: 'http://www.dumbocms.com/'
  app_header_red: 'Dumbo'
  app_header_white: 'CMS'
  frontpage_slug: 'frontpage'
  not_found_slug: 'not_found'
  http_server: 'Apache/1.3.27 (Unix) (Red-Hat/Linux)'
  codename: 'UpperEast'
  version: '2.4'
  milestone: 'Graf'
  rackspace_cloud_username: 'elcanadel'
  rackspace_cloud_api_key: '1d2ec0e97b15b221902a0a48c6d465d1'
  hostname: 'dumbocms.com'
  www_hostname: 'www.dumbocms.com'
  robots_txt: "User-Agent: *\r\nDisallow: /admin/\r\n"
  permalinks: "/%category%/%slug%"
  noc_subject_prefix: '[DumboCMS] '
  noc_sender_name: 'Dumbo'
  noc_sender_address: 'noreply+developers@dumbocms.com'
  noc_recipients: "maurycypw@gmail.com"
  templates_path: '/home/dumbocms/ftp/templates/'
  ftp_templates_path: '/home/dumbocms/ftp/templates/'
  ftp:
    uid: 1001 # dumbocms on uppereast
    gid: 1001 # dumbocms on uppereast